### ISSUE TITLE
Meta issue

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity-extension#1]
- [ ] Find all possible id-links
- [ ] Send the links to background script for processing
- [ ] Background script does the lookups and returns results
- [ ] Content script augments a DOM nodes
